[package]
name = "rust_eze"
version = "0.1.0"
edition = "2021"


[dependencies]
chrono = "0.4"
otpauth = "0.5.1"
qrcode = "0.12"
actix-web = "4.0"
serde = { version = "1.0", features = ["derive"] }
rand = "0.8"
base32 = "0.4"


